definitions:
  dto.CommentUser:
    properties:
      nickname:
        description: 닉네임
        type: string
      profile_image:
        description: 프로필이미지
        type: string
    type: object
  dto.DeleteInterestDto:
    properties:
      date:
        type: string
      symbol:
        type: string
    type: object
  dto.GoogleDto:
    properties:
      email:
        type: string
      profile_image:
        type: string
    type: object
  dto.HolidayDto:
    properties:
      date:
        description: 휴일 날짜
        type: string
      name:
        description: 휴일 이름
        type: string
      opened_at:
        description: 시간 [수능일 같은 경우 10시에 개장]
        type: string
      type:
        description: 1인 경우 opened_at 이후에 가능
        type: integer
    type: object
  dto.InterestList:
    properties:
      close:
        description: 등록한 시점의 가격
        type: number
      date_time:
        description: 등록된 시점
        type: string
      market:
        description: 0 KOSPI 1 KOSDAQ
        type: integer
      name:
        description: 종목이름
        type: string
      percent:
        description: 등록한 시점의 등락률
        type: string
      symbol:
        description: 종목코드
        type: string
      ticker:
        $ref: '#/definitions/dto.InterestTickerModel'
      type:
        description: 현재 사용하지 않습니다.
        type: integer
      user:
        $ref: '#/definitions/dto.InterestUserModel'
      volume:
        description: 등록된 시점의 거래량
        type: string
    type: object
  dto.InterestTickerChartModel:
    properties:
      close:
        description: 현재가
        type: number
      percent:
        description: 현재 등락률
        type: string
      volume:
        description: 현재 거래량
        type: string
    type: object
  dto.InterestTickerModel:
    properties:
      homepage:
        description: 홈페이지
        type: string
    type: object
  dto.InterestUserModel:
    properties:
      nickname:
        description: 등록한 사용자의 닉네임
        type: string
    type: object
  dto.NewCommentDto:
    properties:
      comment:
        type: string
      symbol:
        type: string
    type: object
  dto.NicknameDto:
    properties:
      nickname:
        type: string
    type: object
  dto.RegistDto:
    properties:
      email:
        type: string
      mobile:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  dto.SaleInterestDto:
    properties:
      date:
        type: string
      symbol:
        type: string
    type: object
  dto.SetInterestDto:
    properties:
      symbol:
        type: string
    type: object
  dto.TokenDto:
    properties:
      refresh_token:
        type: string
    type: object
  responses.InterestListResponse:
    properties:
      recent:
        $ref: '#/definitions/dto.InterestTickerChartModel'
      ticker:
        $ref: '#/definitions/dto.InterestList'
    type: object
  responses.OneTickerChartResponse:
    properties:
      close:
        description: 종가(현재가)
        type: number
      date:
        description: 날짜
        type: string
      high:
        description: 고가
        type: number
      low:
        description: 저가
        type: number
      open:
        description: 시가
        type: number
      percent:
        description: 등락률
        type: string
      volume:
        description: 거래량
        type: string
    type: object
  responses.OneTickerResponse:
    properties:
      bps:
        type: number
      chart:
        items:
          $ref: '#/definitions/responses.OneTickerChartResponse'
        type: array
      div:
        type: number
      dps:
        type: number
      eps:
        type: number
      homepage:
        description: 홈페이지 (로고 url)
        type: string
      industry:
        type: string
      listing_date:
        description: 상장일
        type: string
      market:
        description: '0 : 코스피 , 1 : 코스닥'
        type: integer
      market_cap:
        description: 시가총액
        type: number
      name:
        description: 종목명
        type: string
      pbr:
        description: 표시
        type: number
      per:
        description: 표시
        type: number
      representative:
        description: 대표자 (표시할 필요없습니다.)
        type: string
      sector:
        description: 표시
        type: string
      settle_month:
        description: 결산월
        type: string
      symbol:
        description: index
        type: string
    type: object
  responses.SearchTickerResponse:
    properties:
      homepage:
        description: 홈페이지 (로고 url)
        type: string
      market:
        description: 0 코스피 , 1 코스닥
        type: integer
      name:
        description: 종목명
        type: string
      symbol:
        description: 코드
        type: string
    type: object
  responses.TickerCommentsResponse:
    properties:
      comment:
        description: 코멘트
        type: string
      comment_id:
        description: 코멘트 uuid 수정이나 삭제시 필요할 수도 있습니다.
        type: string
      created_at:
        description: 코멘트 등록일시
        type: string
      symbol:
        description: 메세지를 뿌려줄 symbol
        type: string
      user:
        $ref: '#/definitions/dto.CommentUser'
    type: object
  responses.TokenResponse:
    properties:
      access_token:
        description: access token
        type: string
      refresh_token:
        description: refresh token
        type: string
    type: object
  responses.UserResponse:
    properties:
      access_token:
        type: string
      created_at:
        description: 가입일
        type: string
      email:
        description: email 마우스 호버시에만 보이게
        type: string
      id:
        type: string
      nickname:
        description: nickname
        type: string
      profile_image:
        description: google login시 받아오는 profile image
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/google:
    post:
      consumes:
      - application/json
      deprecated: true
      description: |-
        2000 성공
        2001 신규 유저 닉네임 입력 화면으로 이동
        4004 missing bodies
      parameters:
      - description: google email , profile_image
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.GoogleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      summary: 구글 로그인
      tags:
      - auth
  /auth/google/token:
    get:
      consumes:
      - application/json
      description: |-
        2000 성공
        2001 신규 유저 닉네임 입력 화면으로 이동
        4004 required token
        4003 not verify id token
      parameters:
      - description: idtoken
        in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      summary: 구글 idtoken
      tags:
      - auth
  /auth/login:
    get:
      consumes:
      - application/json
      deprecated: true
      description: 2000 성공
      parameters:
      - description: email
        in: query
        name: email
        type: string
      - description: key
        in: query
        name: key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      summary: 로그인 -> 테스트 로그인
      tags:
      - auth
  /auth/regist:
    post:
      consumes:
      - application/json
      deprecated: true
      description: |-
        2001 성공
        4001 missing bodies
        4002 Cannot create user
        4003 Type is not match
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.RegistDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      summary: 회원가입
      tags:
      - auth
  /auth/token:
    post:
      consumes:
      - application/json
      description: |-
        2000 성공
        4001 required refresh_token
        4101 required login
        4004 다른 웹에서 로그인되어 있습니다 다시 로그인 해주세요
      parameters:
      - description: refresh token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.TokenDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.TokenResponse'
      summary: 토큰
      tags:
      - auth
  /health/check:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: health check
      tags:
      - health
  /holiday:
    post:
      consumes:
      - application/json
      description: |-
        2000 성공
        4003 missing bodies
        4004 이미 생성된 공휴일
      parameters:
      - description: holiday
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.HolidayDto'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: 공휴일 or 매매 늦게 시작하는 날 설정
      tags:
      - holiday
  /interest:
    delete:
      consumes:
      - application/json
      description: |-
        2000 성공
        4001 missing bodies
        4002 cannot delete[sql]
        4101 required login
      parameters:
      - description: delete interest
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteInterestDto'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: 관심종목 삭제
      tags:
      - interest
    get:
      consumes:
      - application/json
      description: 2000 성공
      parameters:
      - description: offset count
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.InterestListResponse'
            type: array
      summary: 관심종목
      tags:
      - interest
    post:
      consumes:
      - application/json
      description: |-
        2000 성공
        4001 missing bodies
        4002 cannot add ticker
        4101 required login
      parameters:
      - description: add interest
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.SetInterestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.InterestListResponse'
      security:
      - BearerAuth: []
      summary: 관심종목 추가
      tags:
      - interest
  /interest/sale:
    put:
      consumes:
      - application/json
      description: |-
        2000 성공
        4002 missing bodies
        4101 required login
        4004 Cannot sale
        4005 The time to sale has over
      parameters:
      - description: sale interest
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.SaleInterestDto'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: 관심종목 매도
      tags:
      - interest
  /ticker/{symbol}:
    get:
      consumes:
      - application/json
      description: |-
        2000 성공
        4001 required count
        4002 cannot found list
      parameters:
      - description: symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: count
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.OneTickerResponse'
      summary: 종목 가져오기
      tags:
      - ticker
  /ticker/chart/{symbol}:
    get:
      consumes:
      - application/json
      description: |-
        2000 성공
        2001 empty response
        4001 missing count
        4002 date format error yyyy-mm-dd
      parameters:
      - description: symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: 마지막 날짜
        in: query
        name: date
        type: string
      - description: count
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.OneTickerChartResponse'
            type: array
      summary: 종목 차트 가져오기
      tags:
      - ticker
  /ticker/comment:
    post:
      consumes:
      - application/json
      description: |-
        2000 성공
        4101 required login
        4003 empty comment or symbol
        4004 missing bodies
      parameters:
      - description: ticker comment
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.NewCommentDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TickerCommentsResponse'
            type: array
      security:
      - BearerAuth: []
      summary: 티커 코멘트 등록
      tags:
      - comment
  /ticker/comment/{symbol}:
    get:
      consumes:
      - application/json
      description: |-
        2000 성공
        4101 required login
        4004 count , created_at error
      parameters:
      - description: symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: count
        in: query
        name: count
        required: true
        type: integer
      - description: created_at
        in: query
        name: created_at
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TickerCommentsResponse'
            type: array
      summary: 티커 코멘트 목록
      tags:
      - comment
  /ticker/search:
    get:
      consumes:
      - application/json
      description: |-
        2000 성공
        4001 offset and count are int type
      parameters:
      - description: 검색할 종목명 , 코드
        in: query
        name: word
        required: true
        type: string
      - description: 가지고 있는 list.length
        in: query
        name: offset
        type: integer
      - description: count
        in: query
        name: count
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.SearchTickerResponse'
            type: array
      summary: 종목 검색
      tags:
      - ticker
  /user/nickname:
    put:
      consumes:
      - application/json
      description: |-
        2000 성공
        2001 nickname is exists
        4001 required nickname
        4101 required login
      parameters:
      - description: nickname
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.NicknameDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      security:
      - BearerAuth: []
      summary: 닉네임 변경
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
